[package]
name = "cargo-metal"
description = "Development tooling for metal-oxide"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
metal-oxide = { workspace = true }

[lints]
workspace = true

