[package]
name = "reduction"
description = "Threadgroup reduction on Metal"
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.metal]
kernels = "../kernels/Cargo.toml"

[dependencies]
metal-oxide.workspace = true

[lints]
workspace = true
